name: PR Status
on:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pr-status:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait for all checks to complete
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delay: 10s
          timeout: 1800s
